### PR TITLE
Revert "Update how to submit blog post"

### PR DESCRIPTION
**Pull request by elletjies**
Reverts carpentries/docs.carpentries.org#885

### CODE REVIEW

**Comment by elletjies** [comment]
@maneesha, @froggleston and I are still working on this PR. Can we revert it back?

**Comment by froggleston** [comment]
Yes, please do revert this as this PR isn't yet complete.

**Comment by maneesha** [comment]
The original PR (#885) was never marked as draft, which is why I took it as ready to merge.  

This PR (#887) is marked as draft.  Can I change the status of this one and merge it? That will revert #885.

**Comment by elletjies** [comment]
Thanks for reverting @maneesha

**Comment by froggleston** [comment]
> The original PR (#885) was never marked as draft, which is why I took it as ready to merge.

Ah I missed that - I'll make sure I check this in future. Thanks Maneesha!

**Pull request merged**
