### PR TITLE
Update submit_blog_post.md

### PR DESCRIPTION
**Pull request by elletjies**
Please delete this line and the text below before submitting your contribution.

---
Thanks for contributing! 

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

---

### CODE REVIEW

**Comment by elletjies** [comment]
@acrall I removed the verbiage on how to create a blog post - as discussed here: https://docs.google.com/document/d/1Ouh3I0ZKO_DZ-n8hgfiKt8IT0sbOlk0Q9U__anU2oGM/edit

**Comment by elletjies** [comment]
The workflow for post a blog post can be found here - https://github.com/carpentries/core-team-wiki/tree/main/community-development/workflows-and-templates

**Comment by maneesha** [comment]
@elletjies  is this ready to merge?

**Comment by maneesha** [comment]
@elletjies or @OscarSiba   Are you able to review/approve this?

**Pull request merged**
