### PR TITLE
Inconsistent wording

### PR DESCRIPTION
**Pull request by danielle06**
Correct wording that is inconsistent from paragraph to paragraph

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @danielle06 !
Tagging @sstevens2  as I have been told any changes to the EC section of the handbook need to be approved by EC.

**Comment by maneesha** [comment]
bump @sstevens2

**Comment by maneesha** [comment]
bump @sstevens2

**Comment by sstevens2** [comment]
This looks good to me.  You can go ahead and merge.

**Pull request merged**
