### PR TITLE
Minor edits to privacy policy

### PR DESCRIPTION
**Pull request by kariljordan**
This PR provides minor edits to spelling and verbiage for consistency, and hyperlinks where missing.

Question about this paragraph:
**What information do we collect?**
Pre- and post-workshop surveys represent a formal part of the workshop training process and  are vital to ensure that our lessons, organisation, Code of Conduct, and workshops adhere  to our vision, mission, and standards. The information collected within these surveys is  anonymised and used in reporting and impact studies.

---

Should it be vision, mission, and **values** (instead of standards)?

### CODE REVIEW

**Comment by kariljordan** [comment]
More questions:

- The top of the page says, "Last updated: 2023-01-31", but does that reflect your recent updates?
- In the [Information You Give Us](https://github.com/carpentries/docs.carpentries.org/blob/froggleston_privacy_policy/topic_folders/policies/privacy.md#information-you-give-us) section, do they also give us information via Slack?
- In the [Workshop Participants](https://github.com/carpentries/docs.carpentries.org/blob/froggleston_privacy_policy/topic_folders/policies/privacy.md#workshop-participants) section under **How is this information used?**, do we need to specify that one of the questions in the pre/post survey asks them to provide a unique identifier? The question reads: 
  - Please enter a unique identifier as follows: Number of siblings (as numeric) + First two letters of the city you were born in (lowercase) + First three letters of your current street (lowercase). Example: If I have 0 siblings, was born in Arlington, and live on Creekwater Street, my unique identifier would be 0arcre. This identifier will be confidential to you and will help us compare your answers with the post-survey.

**Review by froggleston — APPROVED** [review]
Looks good to me - thanks Kari! I'll address your questions in the PR.

**Comment by froggleston** [comment]
1. Yes, the date reflects the recent updates. I'll change this to the current date when the final PR is merged.
2. As Slack is a third party service, we cannot control what information people choose to post on Slack, and have to assume that the information they do post is in the public domain. However I'll see if some clarification can be added that we cannot use that public information posted on Slack without their consent.
3. I don't think we need to mention the specific unique survey ID as long as this isn't able to be paired with identifiable information?

**Comment by kariljordan** [comment]
Thanks, @froggleston! All of this sounds great, and kudos on getting our policy revised.

**Pull request merged**
