### PR TITLE
Update Slack Quick Start Guide

### PR DESCRIPTION
**Pull request by acrall**
Update to Slack Quick Start Guide to address [this issue](https://github.com/carpentries/docs.carpentries.org/issues/928)

### CODE REVIEW

**Comment by karenword** [comment]
@acrall I see the first point and not the second in the issue addressed here - is that intentional?

**Comment by acrall** [comment]
@karenword The guide is not meant to provide information on more advanced features. It is a quick start guide only. From my perspective, Point 2 is addressed with this: "For more detailed information on getting started with or using Slack, including accessibility features, please visit [their website](https://slack.com/help/categories/360000049043)."

**Comment by karenword** [comment]
Ok could I maybe request "including accessibility features and change of contact information"? Sher and I just created a [new template email](https://secure.helpscout.net/settings/saved-replies/99021/3169941) to respond to requests for email address updates, prompting people to remember that they may need to change their address on multiple platforms to stay with us. I think it is ok not to have documentation, but I do want to support them if they are looking for the answer after we put them up to it.

**Comment by acrall** [comment]
@karenword Yes, we can add that wording

**Comment by maneesha** [comment]
Thanks @acrall  and @karenword 
What we should offer in our own documentation to be just the basics to get started, and to refer to Slack's documentation for anything else. Otherwise we end up playing the endless game of keeping our documentation up to date with the official Slack documentation.

Would you consider this ready to merge?

**Pull request merged**
