### PR TITLE
New GitHub label: waiting for response

### PR DESCRIPTION
**Pull request by maxim-belkin**
New label for indicating situations when maintainers are waiting for contributor to respond to their feedback/comments but don't expect any changes to the pull request.

### CODE REVIEW

**Comment by fmichonneau** [comment]
thanks Maxim. I'll add this tag across the lesson repositories soon.

**Comment by fmichonneau** [comment]
I might have pushed the merge button too fast...
How do think this label would differ from:

- `status:changes requested`
   + Hex code: #679F38
   + Short Description: Waiting for Contributor to update PR
   + Long Description: Maintainers have reviewed the pull request, and requested changes. Waiting on the Contributor to implement these changes.

Maybe it'd be best to update the language around this label?

**Comment by maxim-belkin** [comment]
> Maybe it'd be best to update the language around this label?

We don't always request changes when we're waiting for a response from a contributor: "Changes requested" captures a situation when a decision has been made. Proposed label is more appropriate for situations before such a decision is made, e.g. when a contributor hasn't responded to an inquiry from maintainers in a while. Such label could be useful for closing stale issues / PRs.

**Comment by ErinBecker** [comment]
Hi @maxim-belkin - sorry for the delayed response to your issue. @fmichonneau @zkamvar @tobyhodges and I had a chance to discuss this at our Curriculum Team meeting and agree that "waiting for response" is more general. To avoid multiplying issue label too extravagantly, we'd like to replace the "changes requested" label with "waiting for response" as waiting for response covers all situations where changes requested would have been used in the past. Is this something you'd be able/willing to put in a PR for?

**Comment by maxim-belkin** [comment]
Sure, I can do that. Btw, if anyone has a better label name than "waiting for response" -- I'm all ears.

**Pull request merged**
