### PR TITLE
Create brand_identity.md

### PR DESCRIPTION
**Pull request by klbarnes20**
Recommendation to add brand identity section to the Communications section of the handbook.

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks for getting this started @klbarnes20 !
I don't want to publish with the language about "Erin says this and François says that."  

@ErinBecker  @fmichonneau  can we come to agreement about which color we should use?  I'd also like to have content in the font section as well.  I don't know the answer to this myself.

**Comment by fmichonneau** [comment]
I double-checked the color used by the original logo and it's the same used on the website. I edited the PR to reflect this and added the font names used for the website.

**Comment by zkamvar** [comment]
I dug around the main repo and found the fonts that we used listed in the SCSS file:

https://github.com/carpentries/carpentries.org/blob/9c47e1454b0cfb2c18fe8860e141e1b4d4325a21/_sass/_02_settings_typography.scss#L25-L28

```scss
$font-family-sans-serif: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
$font-family-sans-header: "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;
$font-family-serif: "Scope+One", Georgia, Times, serif;
$font-family-monospace: "Lucida Console", Monaco, monospace;
```

and the colors:

https://github.com/carpentries/carpentries.org/blob/7fe69011b98dac28ad88acb1818dfb676bbd84ce/_sass/_01_settings_colors.scss#L36-L41

```scss
/* Software Carpentry colors
---------------------------------------- */


$swc-blue: #071159;       // Software Carpentry dark blue
$swc-blue-med: #394EEF;	  // Brighter version of Software Carpentry blue
$swc-blue-light: #e3e6fd; // Medium version of Software Carpentry blue
```

**Comment by ErinBecker** [comment]
This all looks good to me!

**Comment by maneesha** [comment]
Thanks all for your input. I have updated this page so that rather than only listing the hexcodes, it shows what code is what color.  It may take a few hours for you to see this live, but this is what it will look like:

image

**Pull request merged**
