### PR TITLE
Remove "and Instructors" and add a bullet stating "Evidence of Instructors with the relevant skills and knowledge to support the development of the program"

### PR DESCRIPTION
**Pull request by danielle06**
Suggestion to change the verbiage to "Service to a particular audience of learners" by removing "and Instructors." We want all Instructors to be able to teach all lesson programs.

### CODE REVIEW

**Comment by maneesha** [comment]
Tagging @tobyhodges  for input on behalf of the Curriculum Team (I think it's curriculum team that leads process for new lesson programs?).  Because this is under governance, this might also need EC approval to change.

**Comment by tobyhodges** [comment]
I am fine with this but, even though it is a relatively small change, I agree that it should be approved by the @carpentries/governance-committee too.

**Comment by danielle06** [comment]
Thanks @tobyhodges and @maneesha . Was not 100% sure about the change and think it's a great idea to get EC approval.

**Comment by kariljordan** [comment]
@konrad @yabellini and @annajiat are the members of the EC who are on the governance committee. Pinging them for their approval, although they may need a bit more context @danielle06.

**Comment by danielle06** [comment]
We are moving to a single Instructor badge that is not lesson program specific and trying to remove any language from the handbook and websites that falls under that category. Suggesting the change because it could be confusing; however, I may be overthinking it. Could add a bullet that says something like "proof of Instructors with the skills and interest to initially support the program"

**Comment by tobyhodges** [comment]
I think it would be good to include some wording acknowledging that, although any certified Instructor is _allowed_ to teach workshops for any lesson program, there is a subset of all Instructors who are actually _able_ to do so due to domain knowledge, etc.

(E.g. I am eligible to teach a DC Astronomy workshop, but I would not be comfortable doing so due to lack of experience working with astronomy data.)

I like @danielle06's suggestion to add another point to the list, specifying that any new lesson program would need to be able either to tap into the existing pool of Instructors or have a clear path to adding new Instructors with the relevant experience to the pool (ideally both! 😁).

**Comment by yabellini** [comment]
I agree with Toby's comment.  If we take _instructors_ out of that point, it would be good to add another point to the list with the necessary considerations of having the instructors with the technical knowledge to be able to teach the lesson.

**Comment by konrad** [comment]
Thanks everyone. I am fine wit the suggested change and I also agree to make a dedicated point regarding requirement that instructor have the needed knowledge / skills.

**Comment by maneesha** [comment]
Based on the conversation above, I am not sure what changes are approved.  Would @tobyhodges  or @danielle06  be able to update this PR so it is ready to merge?

**Comment by danielle06** [comment]
Thanks everyone! @maneesha  I have added the bullet as discussed.

**Comment by maneesha** [comment]
@tobyhodges  has noted in slack ([private link](https://swcarpentry.slack.com/archives/G01QPQCS71A/p1669660137974009)) that this is good to merge.

**Pull request merged**
