### PR TITLE
Standardize the use of CoC committee

### PR DESCRIPTION
**Pull request by arunkannawadi**
The incident response page has a variety of usages for CoCc as CoC committee, Code of Conduct committee and Code of Conduct Committee. This commit standardizes them throughout the document.

### CODE REVIEW

**Comment by maneesha** [comment]
Assigning to @acrall as CoC Core Team Liason.

**Comment by arunkannawadi** [comment]
I am also happy to change the commit to say CoC committee everywhere consistently. My main reason to raise a PR here was because CoCc was never defined but used a few times.

**Comment by maneesha** [comment]
Bumping this @acrall

**Comment by maneesha** [comment]
Reminder @acrall

**Review by acrall — APPROVED** [review]
Thanks for noticing this @arunkannawadi! I have no concerns with these changes

**Comment by acrall** [comment]
@maneesha Apologies. Feel free to merge

**Pull request merged**
