### PR TITLE
Added online workshops blog post prompts

### PR DESCRIPTION
**Pull request by elletjies**

### CODE REVIEW

**Comment by serahrono** [comment]
@elletjies  thanks for adding these prompts. I would suggest adding them after this section instead https://docs.carpentries.org/topic_folders/hosts_instructors/resources_for_online_workshops.html#blog-posts so they are easier to find

**Comment by elletjies** [comment]
@serahrono just checking at the CDT we discussed adding to the prompts to blog resources page and then linking them to them back on the online resources page. What you are suggestion is rather post the prompts to the online resources page?

**Comment by serahrono** [comment]
Hi @elletjies, I think it might make it easier for people to find and use the prompts if we place them in the Online Workshops resources page. I'll defer to your and @kmomar's decision on this, let me know what you think.

**Comment by elletjies** [comment]
Thank for clarifying :) @serahrono. Will wait for @kmomar to chime in.

**Comment by kmomar** [comment]
Hello, Yes let's go ahead and put them in the Online Workshops resources page. I will send out comms alerting the community about this availability.

**Comment by elletjies** [comment]
@omar and @serahrono awesome! Will make the changes tomorrow!

**Comment by serahrono** [comment]
@elletjies will you be able to move the prompts to a new subsection under this section - https://docs.carpentries.org/topic_folders/hosts_instructors/resources_for_online_workshops.html#blog-posts?

**Comment by serahrono** [comment]
closing as requested changes live here #644

**Pull request closed without merging**
