### PR TITLE
Frequency of Meetings

### PR DESCRIPTION
**Pull request by danielle06**
Change from monthly to quarterly meetings

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @danielle06 !
Tagging @sstevens2  as I have been told any changes to the EC section of the handbook need to be approved by EC.

**Comment by maneesha** [comment]
bump @sstevens2

**Comment by maneesha** [comment]
bump @sstevens2

**Comment by sstevens2** [comment]
Thanks for this change.  Looks good to merge.

**Pull request merged**
