### PR TITLE
add emphasis to microphone item

### PR DESCRIPTION
**Pull request by karenword**
Because inability to hear was the most frequently cited accessibility barrier in our assessment report, this adds detail and a link to the assessment report. Tried to add all this without blowing up the list... edits welcome!

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @karenword 
Did you mean to link to our pre/post survey report? I'm not sure how that directly relates to using a microphone.

**Comment by karenword** [comment]
Yes -- the report details feedback on accessibility and indicates that the most common problem cited is inability to hear at the back of the room. I am adding those details to the Instructor Training curriculum; it didn't all seem to fit here, but I thought linking it would make the implication clear. Based on your response I'm not sure I was successful on that last point, so let me know what you think!

**Comment by maneesha** [comment]
I see, thanks @karenword 
Yes, there is mention in the report about being able to hear the instructors but it's not immediately apparent that this is what is being referred to.  I tweaked the text a little to make it clearly refer to findings from the report. What do you think?

**Comment by karenword** [comment]
lgtm - thanks @maneesha !

**Pull request merged**
