### PR TITLE
Add Fundraising Section to Handbook

### PR DESCRIPTION
**Pull request by kmomar**

### CODE REVIEW

**Comment by maneesha** [comment]
There will be some updates on the technical end that are required to make this display.  I will take care of those after @kariljordan  has approved the content, and merge after that.

**Comment by maneesha** [comment]
No worries @kmomar ! It's not a big deal; I just don't want to change anything while content might still change.  It's mostly about making sure the folder has a properly formatted index page.

**Review by kariljordan — APPROVED** [review]
Thank you so much @kmomar for this PR. It's exactly what I envisioned.

**Comment by maneesha** [comment]
I made a bunch of changes to ensure the site was building correctly with the new Fundraising section.  I also made some misc. formatting updates to fix things like links and line breaks.

I discussed this with @kmomar  because one of the pages here completely duplicated content on [The Carpentries website sponsorship page](https://carpentries.org/sponsorship/).  Because duplication like this makes it difficult to keep things up to date as they change, I recommended linking to The Carpentries website from the handbook.  I've removed the duplicate content from [this file in this PR](https://github.com/carpentries/docs.carpentries.org/blob/update-fundraising-resources-sections/topic_folders/fundraising/carpentries-sponsorship-program.md) and put in placeholder language that Omar will update after talking with Kari.  Omar, you can either update that file directly or share the language you'd like to see there and I'll take care of it - either way is fine.  Thanks!

**Comment by kmomar** [comment]
> Bump @kmomar

Should be ready now

**Pull request merged**
