### PR TITLE
Update coc-governance.md

### PR DESCRIPTION
**Pull request by acrall**
Added updates to CoC governance document based on feedback from committee at 7 July meeting. Still need to add "Communication and collaboration spaces" after receiving additional feedback from committee members

### CODE REVIEW

**Comment by maneesha** [comment]
@acrall I have marked this a draft as you noted you still have to add more to it. Let me know when it's ready to merge.

**Comment by acrall** [comment]
@maneesha I removed it from draft because I recently added the section I mentioned in the first commit. It's ready for review by @dsarahstamps

**Comment by maneesha** [comment]
@acrall I am keeping this as draft. Draft state does not prevent review and edit; it prevents merging.

**Comment by acrall** [comment]
@dsarahstamps Please review this pull request

**Review by dsarahstamps — APPROVED** [review]
Nice work. Thank you. I think the part about the Chair needing to break any ties isn't necessary anymore with our odd numbered IRG, but this comment doesn't detract from the overall governance document.

**Comment by maneesha** [comment]
@acrall @dsarahstamps is this ready to merge?

**Comment by acrall** [comment]
@maneesha Yes, thank you!

**Pull request merged**
