### PR TITLE
Remove "and Instructors"

### PR DESCRIPTION
**Pull request by danielle06**
Suggestion to change the verbiage to "Service to a particular audience of learners" by removing "and Instructors." We want all Instructors to be able to teach all lesson programs.

### CODE REVIEW

**Comment by maneesha** [comment]
Tagging @tobyhodges  for input on behalf of the Curriculum Team (I think it's curriculum team that leads process for new lesson programs?).  Because this is under governance, this might also need EC approval to change.

**Comment by maneesha** [comment]
Bump @tobyhodges

**Comment by tobyhodges** [comment]
This is ok from the Curriculum Team side. I agree that it probably needs @carpentries/executive-council approval, though.

It is very closely related to the discussion in #862, but IMO we do not need the extra bullet in this case because the description here is about lesson programs that already exist, as opposed to the criteria that need to be fulfilled by potential new lesson programs.

A note, to @danielle06: as the line being changed is a quote of [the _Roles and Responsibilities of Lesson Programs_ section of the Bylaws](https://docs.carpentries.org/topic_folders/governance/bylaws.html#roles-and-responsibilities-of-lesson-programs) it is probably best to also suggest the equivalent change to that section of the Bylaws in this pull request as well.

**Comment by tobyhodges** [comment]
I believe the issue is with the word "specific": because The Carpentries now has a single, unified Instructor certification - i.e. we make no distinction between a Data Carpentry Instructor, a Library Carpentry Instructor, and a Software Carpentry Instructor - we should not say that a lesson program caters to a _specific_ set of Instructors. (Though of course a lesson program definitely _should_ cater to Instructors more generally e.g. by providing Instructor Notes in their curriculum, preparing and delivering Instructor onboarding, etc.) 

See #862 for discussion on a similar change.

Tagging @carpentries/core-team-workshop-admin for additional perspective and context.

**Comment by danielle06** [comment]
I have changed the pull request to also delete "and instructors" in the bylaws

**Comment by sstevens2** [comment]
Thanks @danielle06 for your edit to the PR to include the by-laws section.  Changes to the by-laws require EC approval.  We are meeting today and have a full agenda so we won't be able to get this a motion on this change on the agenda until Feb 2023.

I don't feel that this language restricts instructors based on how they were badged originally.  My reading of it aligns "particular" similarly to the learners in that point to mean "service to instructors/learners who are interested in that lesson program or who would benefit from the curricula in that lesson program".  I'm not opposed to this change but am not sure it is needed.  If the @carpentries/core-team-workshop-admin decides this change is needed, I recommend a review of the by-laws for other language changes related to the single badging or for clarity and this change be bundled with other similar changes.  We would like to change the by-laws infrequently in the future so bundling will help prevent frequent small changes.

**Comment by kariljordan** [comment]
The governance committee meets on March. Since we weren't able to get this on the agenda for the Q1 meeting, I will ask them to entertain a motion via email.

**Comment by yabellini** [comment]
The motion passed on the EC with eight positive votes. We can merge this PR.

**Review by kariljordan — APPROVED** [review]

**Pull request merged**
