### PR TITLE
Update cancellations_and_makeups.md

### PR DESCRIPTION
**Pull request by sheraaronhurt**
Update the no show, partial absence and retaking a training

### CODE REVIEW

**Comment by elletjies** [comment]
@sheraaronhurt according to the Style Guide (https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html) we favour UK English over US English. I have made some updates to the text

**Comment by sheraaronhurt** [comment]
@maneesha after you review, if no changes are needed, its good to go :)

**Comment by maneesha** [comment]
@sheraaronhurt  in most places it says that requests must be received within 7 days, but in one place it says 30 days.  Is it supposed to be like that?

**Comment by sheraaronhurt** [comment]
@maneesha great catch. I made the update to 7 that was it is consistent.

**Pull request merged**
