### PR TITLE
Second set of 2020 amendments

### PR DESCRIPTION
**Pull request by lexnederbragt**
The following amendments are proposed:

* Change "Lesson Program Committee" to "Curriculum Advisory Committee"
* Clarify role(s) of the Executive Council
  * Add "Write, maintain and update the bylaws" to the responsibilities 
  * Add a link to more detailed description of roles
  * Add term limits for Executive Council members (maximum of three consecutive 2 year terms, followed by at least a one year hiatus)
* Rewritten section on Committees to a section on Committees and Task Forces
  * clarify their formation
  * added links to the Committee Policy and Task Force Policy
  * added information on the CarpentryCon Task Force
* Update heading of section on Organisational Members to better reflect content
* Clarify rules for Individual (voting) membership based on community contribution

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks @lexnederbragt 
Are these changes ready to merge or just proposed and awaiting review/approval?

**Comment by lexnederbragt** [comment]
These should first be formally approved by voting by the Executive Council. This is planned to happened at the October 22nd EC meeting.

**Review by konrad — APPROVED** [review]

**Review by amyehodge — APPROVED** [review]

**Review by orchid00 — APPROVED** [review]

**Review by joslynnlee — APPROVED** [review]

**Comment by maneesha** [comment]
I see 4 members of the EC have approved this PR.  Is that enough for this to be merged?

**Comment by lexnederbragt** [comment]
In principle yes. But I have just asked the rest of EC to vote to get as high a count as possible. I'll merge once we are done voting.

**Pull request merged**
