### PR TITLE
suggesting the addition of an accessibility label

### PR DESCRIPTION
**Pull request by serahrono**

### CODE REVIEW

**Comment by serahrono** [comment]
moving PR here as per @fmichonneau's suggestion in https://github.com/carpentries/docs.carpentries.org/pull/704

**Comment by fmichonneau** [comment]
excellent, thank you!

**Comment by fmichonneau** [comment]
I'll push this label across our repositories next week.

**Comment by serahrono** [comment]
🚀 thank you @fmichonneau!

**Pull request merged**
