### PR TITLE
Update financial reporting timeline

### PR DESCRIPTION
**Pull request by Talishask**
We are on a 2 month delayed reporting system. CI provides us information for each month at the end of the following month, so the earliest we can report this information to the EC will be at their meeting 2 months later. I have included monthly and quarterly reporting dates, as well as our goal for the draft of the annual financial report. Please feel free to adjust the level of detail, remove the monthly reporting, etc.

### CODE REVIEW

**Comment by lexnederbragt** [comment]
Thanks, @Talishask. However, I'd appreciate it if we could stick to Q1, Q2, Q3 and Q4 reporting, rather than 'Month X financials", unless there is a reason makes this not feasible. This because the budget also has a Quarterly Overview.

**Comment by Talishask** [comment]
HI @lexnederbragt - were you able to make that update or would you like me to make an update to remove the monthly dates?

**Comment by lexnederbragt** [comment]
@Talishask I'd appreciate it if you could make that change, so we're certain all information is accurate. Thanks in advance!

**Comment by maneesha** [comment]
@Talishask  @lexnederbragt  let me know when this is ready to merge

**Comment by Talishask** [comment]
@lexnederbragt  - I've updated the timeline. Let me know if you need anything else.

**Comment by lexnederbragt** [comment]
Perfect! Thanks, @Talishask. Ready to merge now.

**Pull request merged**
