### PR TITLE
Accessibility Changes

### PR DESCRIPTION
**Pull request by brynnelliott**
Accessibility changes - edited sensory words, updated for compatibility of style guide

### CODE REVIEW

**Comment by maneesha** [comment]
Thanks for this @brynnelliott 
I see a review from @sheraaronhurt  was requested so I want to make sure she sees this before we merge.  

I am also very excited to learn more about the changes you have recommended and how they impact accessibility for a global community!

**Comment by maneesha** [comment]
Bumping this as review from @sheraaronhurt  was requested.

**Comment by sheraaronhurt** [comment]
Thanks @maneesha  will get on this immediately.

**Comment by sheraaronhurt** [comment]
All good to go! Thanks so much @brynnelliott

**Pull request merged**
