### PR TITLE
Streamline EC section

### PR DESCRIPTION
**Pull request by maneesha**
This attempts to fix the concerns raised in #731 by re-organizing the files and content in the governance section.  The new menu will look like this: 
image

### CODE REVIEW

**Comment by lexnederbragt** [comment]
Please see https://github.com/carpentries/docs.carpentries.org/issues/731#issuecomment-858648102.

**Comment by lexnederbragt** [comment]
I have given my opinion in the comment linked to above. But I am biased as I wrote the original pages. I'd like to leave it up to others to decide whether these changes are OK, should not be done, or whether a rewrite is necessary.

**Comment by maneesha** [comment]
Thanks @lexnederbragt 
It would be great to hear from @orchid00 as the person who raised the original issue.  I will leave this open for now.

**Comment by maneesha** [comment]
Since we don't seem to have consensus here, I am going to close this PR in favor of leaving issue #731 open for discussion.

**Pull request closed without merging**
