### PR TITLE
Home page headings

### PR DESCRIPTION
**Pull request by maneesha**
Addresses #271

### CODE REVIEW

**Comment by maneesha** [comment]
Reminder @OscarSiba

**Comment by maneesha** [comment]
@OscarSiba to be prepared for the launch, I am going to merge this since it is a small change.

**Comment by OscarSiba** [comment]
Please go ahead and merge. Thanks @maneesha.

**Comment by maneesha** [comment]
This was already merged.  Thanks @OscarSiba

**Pull request merged**
