### PR TITLE
Avoid label fatigue/overload

### PR DESCRIPTION
**Pull request by katrinleinweber**
Dear @tracykteal and @fmichonneau,

because the discussion in the ["Harmonize issue labels"-GDoc](https://docs.google.com/document/d/1b3nIZ6N4IHY24JmLNQ5rkwUACEVS9Hls3auzZD7zHqk/edit) seems to be stalling a bit, here is a suggestion to keep the workflow as light-weight as possible.

The Carpentry-specific labels that are suggested/remaining in #169 would still bring their count up to _more than twice_ the number that GitHub displays immediately in the selector (8):

screen shot 2018-03-29 at 15 50 31

So, my suggestion would be to whittle them down further to a maximum of 12 _in total_. Same for the description: we have ca. 40 characters to convey each label's purpose exactly in the moment that counts: when the maintainer assigns them.

_More_ will only lead to exactly the effects visible in the repos listed in the [GDoc's "interesting […] labels"](https://docs.google.com/document/d/1b3nIZ6N4IHY24JmLNQ5rkwUACEVS9Hls3auzZD7zHqk/edit#heading=h.lr6uzw4082w2) section: a [large](https://github.com/Data4Democracy/internal-displacement/issues?q=no%3Alabel) [fraction](https://github.com/akka/akka/issues?utf8=%E2%9C%93&q=no%3Alabel) of [unlabelled](https://github.com/pandas-dev/pandas/issues?q=no%3Alabel) [issues](https://github.com/matplotlib/matplotlib/issues?utf8=%E2%9C%93&q=no%3Alabel). In other words: label fatigue/overload.

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Suggestions to whittle this down further:

- [ ] remove `type` (Label should intuitively complete a sentence like "This issue/PR **is** a/about ...".) => Wouldn't break [carpenter/github_labels.R L115-119](https://github.com/fmichonneau/carpenter/blob/master/R/github_labels.R#L115-L119) AFAIK, would it?
- [ ] remove `bug-bbq` (Not mentioned in the [blog](https://software-carpentry.org/blog/2018/03/bug-bbq.html) [posts](https://carpentries.github.io/2018-04-bug-bbq/); Better to encourage work on `bug`, `help wanted`, `good first issue`, etc.)
- [ ] remove `need-more-info` (Needs to be specified in a reply/comment anyway; Issue can then be left alone until that info is delivered.)

Also, in order for `carpenter::create_github_labels(…, delete_previous = TRUE)` to work as designed currently, GitHub's default labels need to be added to [/data/github_labels.csv](https://github.com/carpentries/handbook/blob/master/data/github_labels.csv), correct?

**Comment by katrinleinweber** [comment]
Conflict results from #169.

**Comment by remram44** [comment]
I very much agree! If gathering statistics from the issues is not a primary purpose, categorizing issues into types if not very useful.

I also don't understand the difference between "block" and "wait", or see the need to distinguish "changes requested"/"need more info" (it's all "waiting on author").

**Comment by maneesha** [comment]
Assigning to @fmichonneau  as he has been managing labels for all our other repos

**Comment by remram44** [comment]
It's a bit late as the labels have already been rolled out. Having to label issues on my lesson repos now, the problems I listed above are very apparent.

**Comment by remram44** [comment]
It seems to me that "template-and-tools", "documentation", "instructor-guide" should really not be "type". An enhancement can concern documentation, a clarification can be about the instructor guide, and so those are orthogonal things.

**Comment by katrinleinweber** [comment]
Depends on the error/mistake, I would say: "factually incorrect info" would qualify as `bug`, IMHO. Otherwise, I agree, and have updated the "lightweight" suggestions.

**Comment by remram44** [comment]
That's what I've been doing, but we might as well match the language of the labels to *lessons*, since it what our repositories are.

**Comment by maneesha** [comment]
Per @fmichonneau  this will require further discussion with him and @ErinBecker

**Comment by ErinBecker** [comment]
Thanks for the ping @maneesha. We have a lot of lessons that are planning to go through lesson release in the next couple of months (for a June release). Since the Maintainers on those lessons will be working a lot on their repos over the next couple of months, I think it makes sense to get feedback from Maintainers after the June release on how the issue labels have been working for them and then use that feedback to update these labels in August or so. So let's leave this open for now.

**Comment by maneesha** [comment]
@fmichonneau @ErinBecker @tobyhodges @zkamvar Would the Curriculum Team like to keep this open?

**Comment by maneesha** [comment]
I am closing this PR because it is old and we are transitioning to a new handbook.  I am opening an issue in the new handbook repo (https://github.com/carpentries/handbook-beta/issues/204) to consider this again.

**Pull request closed without merging**
